[project]
name = "rlhf-maker"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
rlhf-make = "rlhf_maker.generate_rlhf:main"

[tool.setuptools]
package-dir = {"" = "src"}
